// @ts-nocheck

/** biome-ignore-all lint: auto generated file, do not modify */

/** biome-ignore-all assist/source/organizeImports: auto generated file, do not modify */

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as RecorderRouteImport } from './routes/recorder';
import { Route as IndexRouteImport } from './routes/index';

const RecorderRoute = RecorderRouteImport.update({
  id: '/recorder',
  path: '/recorder',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/recorder': typeof RecorderRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/recorder': typeof RecorderRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/recorder': typeof RecorderRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/recorder';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/recorder';
  id: '__root__' | '/' | '/recorder';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  RecorderRoute: typeof RecorderRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recorder': {
      id: '/recorder';
      path: '/recorder';
      fullPath: '/recorder';
      preLoaderRoute: typeof RecorderRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecorderRoute: RecorderRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
