// @ts-nocheck

/** biome-ignore-all lint: auto generated file, do not modify */

/** biome-ignore-all assist/source/organizeImports: auto generated file, do not modify */

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as LayoutRouteImport } from './routes/_layout';
import { Route as IndexRouteImport } from './routes/index';
import { Route as ApiExerciseTypesRouteImport } from './routes/api/exercise-types';
import { Route as LayoutRecorderRouteImport } from './routes/_layout/recorder';

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiExerciseTypesRoute = ApiExerciseTypesRouteImport.update({
  id: '/api/exercise-types',
  path: '/api/exercise-types',
  getParentRoute: () => rootRouteImport,
} as any);
const LayoutRecorderRoute = LayoutRecorderRouteImport.update({
  id: '/recorder',
  path: '/recorder',
  getParentRoute: () => LayoutRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/recorder': typeof LayoutRecorderRoute;
  '/api/exercise-types': typeof ApiExerciseTypesRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/recorder': typeof LayoutRecorderRoute;
  '/api/exercise-types': typeof ApiExerciseTypesRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_layout': typeof LayoutRouteWithChildren;
  '/_layout/recorder': typeof LayoutRecorderRoute;
  '/api/exercise-types': typeof ApiExerciseTypesRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/recorder' | '/api/exercise-types';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/recorder' | '/api/exercise-types';
  id: '__root__' | '/' | '/_layout' | '/_layout/recorder' | '/api/exercise-types';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  LayoutRoute: typeof LayoutRouteWithChildren;
  ApiExerciseTypesRoute: typeof ApiExerciseTypesRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof LayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/exercise-types': {
      id: '/api/exercise-types';
      path: '/api/exercise-types';
      fullPath: '/api/exercise-types';
      preLoaderRoute: typeof ApiExerciseTypesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_layout/recorder': {
      id: '/_layout/recorder';
      path: '/recorder';
      fullPath: '/recorder';
      preLoaderRoute: typeof LayoutRecorderRouteImport;
      parentRoute: typeof LayoutRoute;
    };
  }
}

interface LayoutRouteChildren {
  LayoutRecorderRoute: typeof LayoutRecorderRoute;
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutRecorderRoute: LayoutRecorderRoute,
};

const LayoutRouteWithChildren = LayoutRoute._addFileChildren(LayoutRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  ApiExerciseTypesRoute: ApiExerciseTypesRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
